// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFile() {
  return window['go']['main']['Croc']['OpenFile']();
}

export function ReceiveCode(arg1) {
  return window['go']['main']['Croc']['ReceiveCode'](arg1);
}

export function SendFile(arg1) {
  return window['go']['main']['Croc']['SendFile'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['Croc']['Startup'](arg1);
}
