// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckInstall() {
  return window['go']['main']['Install']['CheckInstall']();
}

export function Install() {
  return window['go']['main']['Install']['Install']();
}

export function SelectFolder() {
  return window['go']['main']['Install']['SelectFolder']();
}

export function Startup(arg1) {
  return window['go']['main']['Install']['Startup'](arg1);
}
